language: php

php:
    - 7.1
    - 7.2

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update
    - if [ "$STABILITY" = "dev" ]; then composer config minimum-stability dev; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
    - composer install

script:
    - vendor/bin/phpunit --coverage-text
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index.html
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index-with-es5-shim.html

matrix:
    fast_finish: true
    include:
      - php: 7.2
        env: SYMFONY_VERSION='~4.1.0'
      - php: 7.2
        env: SYMFONY_VERSION='~4.2.0'
      - php: 7.2
        env: SYMFONY_VERSION='~4.3.0'
      - php: 7.2
        env: SYMFONY_VERSION='~4.4.0'
      - php: 7.2
        env: SYMFONY_VERSION='~5.0.0'
      - php: 7.2
        env: STABILITY=dev
